version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: docker/app.dockerfile
    image: apresentar-app
    container_name: apresentar_app
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    expose:
      - "9000"

  web:
    image: nginx:stable-alpine
    container_name: apresentar_web
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx.dev.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app
